// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SubSystem.proto
#ifndef GRPC_SubSystem_2eproto__INCLUDED
#define GRPC_SubSystem_2eproto__INCLUDED

#include "SubSystem.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace SubSystemSink {

class SubSystemServer final {
 public:
  static constexpr char const* service_full_name() {
    return "SubSystemSink.SubSystemServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::SubSystemSink::SubSystemTemp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SubSystemSink::SubSystemTemp>> AsyncGetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SubSystemSink::SubSystemTemp>>(AsyncGetSubSystemTempRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SubSystemSink::SubSystemTemp>> PrepareAsyncGetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::SubSystemSink::SubSystemTemp>>(PrepareAsyncGetSubSystemTempRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SubSystemSink::SubSystemTemp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void GetSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SubSystemSink::SubSystemTemp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SubSystemSink::SubSystemTemp>* AsyncGetSubSystemTempRaw(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::SubSystemSink::SubSystemTemp>* PrepareAsyncGetSubSystemTempRaw(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::SubSystemSink::SubSystemTemp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SubSystemSink::SubSystemTemp>> AsyncGetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SubSystemSink::SubSystemTemp>>(AsyncGetSubSystemTempRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SubSystemSink::SubSystemTemp>> PrepareAsyncGetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::SubSystemSink::SubSystemTemp>>(PrepareAsyncGetSubSystemTempRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response, std::function<void(::grpc::Status)>) override;
      void GetSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SubSystemSink::SubSystemTemp* response, std::function<void(::grpc::Status)>) override;
      void GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void GetSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SubSystemSink::SubSystemTemp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::SubSystemSink::SubSystemTemp>* AsyncGetSubSystemTempRaw(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::SubSystemSink::SubSystemTemp>* PrepareAsyncGetSubSystemTempRaw(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetSubSystemTemp_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetSubSystemTemp() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSubSystemTemp(::grpc::ServerContext* context, ::SubSystemSink::empty_param* request, ::grpc::ServerAsyncResponseWriter< ::SubSystemSink::SubSystemTemp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetSubSystemTemp<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_GetSubSystemTemp() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::SubSystemSink::empty_param, ::SubSystemSink::SubSystemTemp>(
          [this](::grpc::ServerContext* context,
                 const ::SubSystemSink::empty_param* request,
                 ::SubSystemSink::SubSystemTemp* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->GetSubSystemTemp(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_GetSubSystemTemp(
        ::grpc::experimental::MessageAllocator< ::SubSystemSink::empty_param, ::SubSystemSink::SubSystemTemp>* allocator) {
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SubSystemSink::empty_param, ::SubSystemSink::SubSystemTemp>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_GetSubSystemTemp<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetSubSystemTemp() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetSubSystemTemp() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSubSystemTemp(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_GetSubSystemTemp() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GetSubSystemTemp(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_GetSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetSubSystemTemp(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetSubSystemTemp : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetSubSystemTemp() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::SubSystemSink::empty_param, ::SubSystemSink::SubSystemTemp>(std::bind(&WithStreamedUnaryMethod_GetSubSystemTemp<BaseClass>::StreamedGetSubSystemTemp, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetSubSystemTemp() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetSubSystemTemp(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SubSystemSink::empty_param,::SubSystemSink::SubSystemTemp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetSubSystemTemp<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetSubSystemTemp<Service > StreamedService;
};

}  // namespace SubSystemSink


#endif  // GRPC_SubSystem_2eproto__INCLUDED
