// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SubSystem.proto

#include "SubSystem.pb.h"
#include "SubSystem.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace SubSystemSink {

static const char* SubSystemServer_method_names[] = {
  "/SubSystemSink.SubSystemServer/GetSubSystemTemp",
};

std::unique_ptr< SubSystemServer::Stub> SubSystemServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SubSystemServer::Stub> stub(new SubSystemServer::Stub(channel));
  return stub;
}

SubSystemServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetSubSystemTemp_(SubSystemServer_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SubSystemServer::Stub::GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::SubSystemSink::SubSystemTemp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetSubSystemTemp_, context, request, response);
}

void SubSystemServer::Stub::experimental_async::GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetSubSystemTemp_, context, request, response, std::move(f));
}

void SubSystemServer::Stub::experimental_async::GetSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SubSystemSink::SubSystemTemp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetSubSystemTemp_, context, request, response, std::move(f));
}

void SubSystemServer::Stub::experimental_async::GetSubSystemTemp(::grpc::ClientContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetSubSystemTemp_, context, request, response, reactor);
}

void SubSystemServer::Stub::experimental_async::GetSubSystemTemp(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::SubSystemSink::SubSystemTemp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetSubSystemTemp_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SubSystemSink::SubSystemTemp>* SubSystemServer::Stub::AsyncGetSubSystemTempRaw(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::SubSystemSink::SubSystemTemp>::Create(channel_.get(), cq, rpcmethod_GetSubSystemTemp_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::SubSystemSink::SubSystemTemp>* SubSystemServer::Stub::PrepareAsyncGetSubSystemTempRaw(::grpc::ClientContext* context, const ::SubSystemSink::empty_param& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::SubSystemSink::SubSystemTemp>::Create(channel_.get(), cq, rpcmethod_GetSubSystemTemp_, context, request, false);
}

SubSystemServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SubSystemServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SubSystemServer::Service, ::SubSystemSink::empty_param, ::SubSystemSink::SubSystemTemp>(
          std::mem_fn(&SubSystemServer::Service::GetSubSystemTemp), this)));
}

SubSystemServer::Service::~Service() {
}

::grpc::Status SubSystemServer::Service::GetSubSystemTemp(::grpc::ServerContext* context, const ::SubSystemSink::empty_param* request, ::SubSystemSink::SubSystemTemp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace SubSystemSink

